name: Push to firestore

on:
  push:
    branches:
      - main
      - preview
  workflow_dispatch:

jobs:
  use_base_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tap CLI
        uses: actions/checkout@v3
        with:
          repository: the-arena-project/tap-cli
          ssh-key: ${{ secrets.CLI_PRIVATE_DEPLOY_KEY }}
          path: tap-cli
      
      - name: Build tap cli
        run: |
          cd tap-cli
          npm ci
          npm run build

      - name: Install tap cli
        run: |
          cd tap-cli
          sudo cp -r bin/tap /usr/bin/tap

      - name: Cleanup tap cli
        run: |
          rm -rf tap-cli

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure tap cli
        run: |
          tap config set backendUrl ${{ secrets.BACKEND_URL }}
          tap config set backendApiKey ${{ secrets.BACKEND_API_KEY }}

      - name: push to firestore as preview
        if: github.ref == 'refs/heads/preview'
        run: |
          for trackModelId in $(tap track ls); do
            tap track r push "$trackModelId" --preRelease
          done

      - name: push to firestore as production
        if: github.ref == 'refs/heads/main'
        run: |
          for trackModelId in $(tap track ls); do
            tap track r push "$trackModelId" --preRelease=false
          done